# cat docker-compose.yml
version: '3.3'
services:
### MySQL Container
  mysql:
    image: testwebappsql
    build:
      args:
        - MYSQL_DATABASE=webapp
        - MYSQL_USER=root
        - MYSQL_PASSWORD=123456
        - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./apps/mysql/db.sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
      - "8000:3000"
      - "8001:4000"
    environment:
      NODE_ENV: production